version: '3.5'

networks:
  test:
    name: nexus1-backend-project


services:
  mysql_db:
    image: mysql:8.0.31
    container_name: mysql-nexus1
    volumes:
      - ./app/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - test
    environment:
      - MYSQL_DATABASE=nexus1
      - MYSQL_USER=nexus1-admin
      - MYSQL_PASSWORD=nexus1-password
      - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  fastapi:
    image: nexus1-backend:latest
    container_name: fastapi-nexus1
    restart: always
    ports: 
      - 8000:8000
    networks:
      - test
    environment:
      - MYSQL_URL=mysql://root:toor@mysql-nexus1:3306/nexus1
    volumes:
      - ./app:/code/app
    depends_on:
      mysql_db:
        condition: service_healthy
    x-develop:
      watch:
        - action: sync
          path: ./app
          target: /code/app
        - action: rebuild
          path: ./app/package.json