name: Build and Deploy Docs

on:
  push:
    branches:
      - develop  # Cambia esto si prefieres otro branch como desencadenante

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Python y Sphinx
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      # 3. Generar la documentación
      - name: Build documentation
        run: |
          cd source
          sphinx-build -b html . ../docs/build/html

      # 4. Deploy a la rama gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
